function grid_config_collection = generate_grid_config_collection(param, arg)

    % Create all grid configurations
    grid_config_collection.grid_config_true_graph = factory_grid_config_true_graph(param.true_graph, arg);
    grid_config_collection.grid_config_corrupted_graph = factory_grid_config_corrupted_graph(param.corrupted_graph, arg);
    grid_config_collection.grid_config_true_signal = factory_grid_config_true_signal(param.true_signal, arg);
    grid_config_collection.grid_config_observation_model = factory_grid_config_observation_model(param.observation_model, arg);
    grid_config_collection.grid_config_optimization = factory_grid_config_optimization(param.optimization, arg);

    % Create a cell of parameter names
    grid_config_collection.parameter_name = [cellfun(@(z) [{"true_graph"}, z], grid_config_collection.grid_config_true_graph.parameter_name, "UniformOutput", false), ...
                                             cellfun(@(z) [{"corrupted_graph"}, z], grid_config_collection.grid_config_corrupted_graph.parameter_name, "UniformOutput", false), ...
                                             cellfun(@(z) [{"true_signal"}, z], grid_config_collection.grid_config_true_signal.parameter_name, "UniformOutput", false), ...
                                             cellfun(@(z) [{"observation_model"}, z], grid_config_collection.grid_config_observation_model.parameter_name, "UniformOutput", false), ...
                                             cellfun(@(z) [{"optimization"}, z], grid_config_collection.grid_config_optimization.parameter_name, "UniformOutput", false)];

    % Create a cell of parameter ranges
    grid_config_collection.parameter_range = [grid_config_collection.grid_config_true_graph.parameter_range, ...
                                              grid_config_collection.grid_config_corrupted_graph.parameter_range, ...
                                              grid_config_collection.grid_config_true_signal.parameter_range, ...
                                              grid_config_collection.grid_config_observation_model.parameter_range, ...
                                              grid_config_collection.grid_config_optimization.parameter_range];

    % Create the grid configuration name
    grid_config_collection.name = [grid_config_collection.grid_config_true_graph.configuration_name, ...
                                   grid_config_collection.grid_config_corrupted_graph.configuration_name, ...
                                   grid_config_collection.grid_config_true_signal.configuration_name, ...
                                   grid_config_collection.grid_config_observation_model.configuration_name, ...
                                   grid_config_collection.grid_config_optimization.configuration_name];

    % Create a "param" struct template
    grid_config_collection.param_template = create_param_template(param, grid_config_collection.parameter_name);

end