function all_grid_config = generate_all_grid_config(param)

    % Get all grid configurations
    all_grid_config.grid_config_true_graph = factory_grid_config_true_graph(param.true_graph, []);
    all_grid_config.grid_config_corrupted_graph = factory_grid_config_corrupted_graph(param.corrupted_graph, []);
    all_grid_config.grid_config_true_signal = factory_grid_config_true_signal(param.true_signal, []);
    all_grid_config.grid_config_observation_model = factory_grid_config_observation_model(param.observation_model, []);
    all_grid_config.grid_config_optimization = factory_grid_config_optimization(param.optimization, []);

    % Create a cell of parameter names
    all_grid_config.parameter_name = [all_grid_config.grid_config_true_graph.parameter_name, ...
                                      all_grid_config.grid_config_corrupted_graph.parameter_name, ...
                                      all_grid_config.grid_config_true_signal.parameter_name, ...
                                      all_grid_config.grid_config_observation_model.parameter_name, ...
                                      all_grid_config.grid_config_optimization.parameter_name];

    % Create a cell of parameter ranges
    all_grid_config.parameter_range = [all_grid_config.grid_config_true_graph.parameter_range, ...
                                       all_grid_config.grid_config_corrupted_graph.parameter_range, ...
                                       all_grid_config.grid_config_true_signal.parameter_range, ...
                                       all_grid_config.grid_config_observation_model.parameter_range, ...
                                       all_grid_config.grid_config_optimization.parameter_range];

    % Create the grid configuration name
    all_grid_config.name = [all_grid_config.grid_config_true_graph.configuration_name, ...
                            all_grid_config.grid_config_corrupted_graph.configuration_name, ...
                            all_grid_config.grid_config_true_signal.configuration_name, ...
                            all_grid_config.grid_config_observation_model.configuration_name, ...
                            all_grid_config.grid_config_optimization.configuration_name];

end